/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FibLib */

#ifndef _Included_FibLib
#define _Included_FibLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FibLib
 * Method:    fibJ
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_FibLib_fibJ
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
